version: '3'

services:
  zkbob-console:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: zkbob-console
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/app/src
      - ./assets:/home/node/app/assets:ro
      - ./client-config-prod.json:/home/node/app/client-config-prod.json
    command: bash -c "echo CONFIG_JSON=./client-config-prod.json > /home/node/app/.env && yarn dev-docker"
