version: '3'

services:
  zkbob-console:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: zkbob-console
    restart: always
    ports:
      - "1234:1234"
    volumes:
      - ./src:/home/node/app/src
      - ./assets:/home/node/app/assets:ro
    environment:
      NETWORK: ${NETWORK}
      RPC_URL: ${RPC_URL}
      RELAYER_URL: ${RELAYER_URL}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      TOKEN_ADDRESS: ${TOKEN_ADDRESS}
      MINTER_ADDRESS: ${MINTER_ADDRESS}
      TRANSACTION_URL: ${TRANSACTION_URL}
      TOKEN_SYMBOL: ${TOKEN_SYMBOL}
      SHIELDED_TOKEN_SYMBOL: ${SHIELDED_TOKEN_SYMBOL}
      DELEGATED_PROVER_URL: ${DELEGATED_PROVER_URL}
      CLOUD_API_ENDPOINT: ${CLOUD_API_ENDPOINT}
      GIFTCARD_REDEMPTION_URL: ${GIFTCARD_REDEMPTION_URL}
    command: yarn dev
