version: '3'

services:
  zkbob-console:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: zkbob-console
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./assets:/usr/share/nginx/html/assets
      - ./client-config.json:/usr/share/nginx/html/client-config.json
    environment:
      CONFIG_JSON: ./client-config.json
    command: yarn dev
