version: '3'

services:
  zkbob-console:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: zkbob-console
    restart: always
    ports:
      - "1234:1234"
    volumes:
      - ./src:/home/node/app/src
      - ./assets:/home/node/app/assets:ro
    environment:
    command: yarn dev
