#!/usr/bin/env bash

USERNAME=evgenkor
IMAGE=zkbob-console
VERSION=3.7.0
TAG=latest

yarn build:prod && \
docker build -f Dockerfile.prod -t $USERNAME/$IMAGE:$TAG . && \
docker tag $USERNAME/$IMAGE:$TAG $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:$TAG && \
docker push $USERNAME/$IMAGE:$VERSION
