#!/usr/bin/env bash

USERNAME=evgenkor
IMAGE=zkbob-console

yarn build:prod && \
docker build -f Dockerfile.prod --platform linux/amd64 -t $USERNAME/$IMAGE:$TAG . && \
docker tag $USERNAME/$IMAGE:$TAG $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:$TAG && \
docker push $USERNAME/$IMAGE:$VERSION
