#!/usr/bin/env bash
cd ../libzkbob-rs/libzkbob-rs-wasm && \
./scripts/build && \
cd -

cd ../zkbob-client-js && \
yarn upgrade libzkbob-rs-wasm-web && \
yarn upgrade libzkbob-rs-wasm-web-mt && \
yarn build && \

cd -
yarn upgrade zkbob-client-js && \
yarn dev
